### PR TITLE
WIP: Upgrade bootstrap to 4.1

### PR DESCRIPTION
**Pull request by kentyunge**
Update to bootstrap 4.1 so we can SASS all the things.  

**Known Issues**: The desktop header links broke when I merged master into the branch.  Haven't been able to debug why as of yet.

### CODE REVIEW

**Comment by egillespie** [comment]
Hi @kentyunge, I liked where this was going so I decided to try finishing it up. I tend to commit frequently so here's the gist of what I did:

1. Use npm dependencies to include jQuery, Popper, and Bootstrap 4 and introduced a custom theme file (`custom-bootstrap-theme.scss`)
2. Use Vue to handle the navigation menu toggle — the new collapsible menu in Bootstrap 4 uses jQuery at load time to try and automatically setup menus, but the component's not ready when this happens, so it wasn't working 😕
3. Style touch-ups to make the site look close to what it is in staging

I was hoping that using Vue for the menu would allow us to remove jQuery altogether, but it looks like the calendar uses a Popper plugin for those hover-over popups. I'm going to hold off on that change for now. 😢 

Let me know what you think!

**Comment by egillespie** [comment]
Hi @kentyunge, I liked where this was going so I decided to try finishing it up. I tend to commit frequently so here's the gist of what I did:

1. Use npm dependencies to include jQuery, Popper, and Bootstrap 4 and introduced a custom theme file (`custom-bootstrap-theme.scss`)
2. Use Vue to handle the navigation menu toggle — the new collapsible menu in Bootstrap 4 uses jQuery at load time to try and automatically setup menus, but the component's not ready when this happens, so it wasn't working 😕
3. Style touch-ups to make the site look close to what it is in staging

I was hoping that using Vue for the menu would allow us to remove jQuery altogether, but it looks like the calendar uses a Popper plugin for those hover-over popups. I'm going to hold off on that change for now. 😢 

Let me know what you think!

**Comment by egillespie** [comment]
Hi @kentyunge, I liked where this was going so I decided to try finishing it up. I tend to commit frequently so here's the gist of what I did:

1. Use npm dependencies to include jQuery, Popper, and Bootstrap 4 and introduced a custom theme file (`custom-bootstrap-theme.scss`)
2. Use Vue to handle the navigation menu toggle — the new collapsible menu in Bootstrap 4 uses jQuery at load time to try and automatically setup menus, but the component's not ready when this happens, so it wasn't working 😕
3. Style touch-ups to make the site look close to what it is in staging, including addressing #54

I was hoping that using Vue for the menu would allow us to remove jQuery altogether, but it looks like the calendar uses a Popper plugin for those hover-over popups. I'm going to hold off on that change for now. 😢 

Let me know what you think!

**Comment by kentyunge** [comment]
@egillespie I think the changes look great.  The only thing I saw that stood out was the mobile menu being right aligned.  I just wanted to make sure that's what you wanted.  If not, I think we can handle this with flexbox and media queries.  Also, the social icons on all on the same line in the mobile menu.  I don't necessarily have a problem with that but the icons may be difficult to touch given they are close together.

**Comment by egillespie** [comment]
@kentyunge Thanks for the feedback. Aligning the dropdown nav links on the right was intentional — with the button being on the right, it seems like access to the links is better if they are on the right as well.

Totally agree on the tiny icons on a single line. They looked much bigger in emulation on my laptop. I'll switch them back to separate lines. I'll also make the text for all items in that dropdown nav bigger.

**Pull request merged**
